Use pre-3.10 serialization code on PyPy3.10
The new serialization code for Python 3.10+ does not seem to work
on PyPy3.10 7.3.13, as it causes:

    ValueError: no signature found for builtin type <class 'code'>

Switch back to the old code if PyPy is used, at least for the time
being.  With this change, the test suite passes on PyPy3.10.

Fixes #845